/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 缩放区域配置 */
export interface ZoomRegion {
  /** 区域 ID */
  id: string
  /** 开始时间 (毫秒) */
  startMs: number
  /** 结束时间 (毫秒) */
  endMs: number
  /** 缩放中心 X (0-1) */
  targetX: number
  /** 缩放中心 Y (0-1) */
  targetY: number
  /** 缩放比例 */
  scale: number
  /** 缓动函数 */
  easing?: string
}
/** 裁剪区域配置 */
export interface CropRegion {
  /** 左边界 (0-1) */
  left: number
  /** 上边界 (0-1) */
  top: number
  /** 右边界 (0-1) */
  right: number
  /** 下边界 (0-1) */
  bottom: number
}
/** 裁剪时间段配置 */
export interface TrimRegion {
  /** 区域 ID */
  id: string
  /** 开始时间 (毫秒) */
  startMs: number
  /** 结束时间 (毫秒) */
  endMs: number
}
/** 标注区域配置 */
export interface AnnotationRegion {
  /** 区域 ID */
  id: string
  /** 标注类型 */
  annotationType: string
  /** 开始时间 (毫秒) */
  startMs: number
  /** 结束时间 (毫秒) */
  endMs: number
  /** X 坐标 (0-1) */
  x: number
  /** Y 坐标 (0-1) */
  y: number
  /** 宽度 (0-1) */
  width?: number
  /** 高度 (0-1) */
  height?: number
  /** 颜色 */
  color?: string
  /** 文本内容 */
  text?: string
  /** 线条宽度 */
  strokeWidth?: number
}
/** 摄像头覆盖层配置 */
export interface CameraOverlay {
  /** 是否启用 */
  enabled: boolean
  /** 摄像头视频路径 */
  videoPath?: string
  /** 形状 (circle/rectangle) */
  shape: string
  /** 大小百分比 */
  size: number
  /** 位置 */
  position: CameraPosition
  /** 透明度 (0-1) */
  opacity: number
  /** 边框样式 */
  borderStyle: string
}
/** 摄像头位置 */
export interface CameraPosition {
  /** X 坐标 (0-1) */
  x: number
  /** Y 坐标 (0-1) */
  y: number
}
/** 导出配置 */
export interface ExportConfig {
  /** 输入视频路径 */
  inputPath: string
  /** 输出视频路径 */
  outputPath: string
  /** 输出宽度 */
  width: number
  /** 输出高度 */
  height: number
  /** 帧率 */
  frameRate: number
  /** 比特率 (bps) */
  bitrate: number
  /** 编码器 (h264/h265/vp9) */
  codec?: string
  /** 壁纸/背景图片路径 */
  wallpaper?: string
  /** 缩放区域 */
  zoomRegions: Array<ZoomRegion>
  /** 裁剪区域 */
  cropRegion?: CropRegion
  /** 时间裁剪 */
  trimRegions: Array<TrimRegion>
  /** 标注 */
  annotationRegions: Array<AnnotationRegion>
  /** 摄像头覆盖 */
  cameraOverlay?: CameraOverlay
  /** 是否显示阴影 */
  showShadow: boolean
  /** 阴影强度 (0-1，与编辑器一致) */
  shadowIntensity: number
  /** 是否显示模糊背景 */
  showBlur: boolean
  /** 是否启用运动模糊 */
  motionBlurEnabled: boolean
  /** 圆角半径 (像素，基于预览尺寸) */
  borderRadius?: number
  /** 内边距 (0-100 百分比) */
  padding?: number
  /** 预览区域宽度 (用于缩放 borderRadius) */
  previewWidth?: number
  /** 首选编码器 (nvenc/qsv/amf/videotoolbox/vaapi/x264) */
  preferredEncoder?: string
  /** 是否使用 GPU 渲染 */
  useGpuRendering?: boolean
  /** 并发线程数 (0 = 自动) */
  concurrency?: number
  /** FFmpeg 可执行文件目录路径 (可选，不指定则使用系统 PATH) */
  ffmpegDir?: string
}
/** 导出进度 */
export interface ExportProgress {
  /** 当前帧 */
  currentFrame: number
  /** 总帧数 */
  totalFrames: number
  /** 进度百分比 (0-100) */
  percentage: number
  /** 当前阶段 */
  stage: string
  /** 预计剩余时间 (秒) */
  estimatedTimeRemaining?: number
  /** 当前处理速度 (帧/秒) */
  fps?: number
}
/** 导出结果 */
export interface ExportResult {
  /** 是否成功 */
  success: boolean
  /** 输出文件路径 */
  outputPath?: string
  /** 错误信息 */
  error?: string
  /** 总耗时 (毫秒) */
  durationMs?: number
  /** 使用的编码器 */
  encoderUsed?: string
  /** 总帧数 */
  totalFrames?: number
}
/** GPU 信息 */
export interface GpuInfo {
  /** 是否支持 GPU 渲染 */
  supported: boolean
  /** GPU 名称 */
  name?: string
  /** 后端类型 (Vulkan/Metal/DX12) */
  backend?: string
  /** 显存大小 (MB) */
  memoryMb?: number
}
/** 初始化日志系统 */
export declare function initLogger(level?: string | undefined | null): void
/** 检查系统支持的硬件编码器 */
export declare function getAvailableEncoders(): Array<string>
/** 检查 GPU 渲染是否可用 */
export declare function checkGpuSupport(): Promise<GpuInfo>
/** 检查 FFmpeg 是否可用 */
export declare function checkFfmpeg(): boolean
/** 获取 FFmpeg 版本 */
export declare function getFfmpegVersion(): string | null
/** 视频导出器 */
export declare class NativeVideoExporter {
  constructor(config: ExportConfig)
  export(progressCallback: (...args: any[]) => any): Promise<unknown>
  cancel(): boolean
  get isRunning(): boolean
}
